const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");

module.exports = {
    data: new SlashCommandBuilder()
    .setName('kill')
    .setDescription('Убий някого')
    .addUserOption(option => option.setName('target').setDescription('Кого искаш да убиеш?').setRequired(true)),
    async execute(interaction) {
        const target = interaction.options.getUser('target');
        const author = interaction.user;

        var kills = [
                
            `след дълъг ден, ${author} сяда на дивана с ${target} и пуска The Big Bang Theory. След шега от Шелдън Купър, ${target} не може да спре да се смее, докато не умре.`,
            `${author} натисна Alt+F4 на ${target}.exe!`,
            `${author} се опита да свири на флейта, което взриви главата на ${target}.`,
            `${author} си спука тъпанчетата, като слушаше музика твърде силно.`,
            `${author} предизвиква ${target} на бой до смърт. ${target} печели.`,
            `${author} отсича главата на ${target} с клавиатура.`,
            `${author} смачква ${target} с хладилник.`,
            `${author} обезглавява ${target} с меч.`,
            `${author} дърпа ушите на ${target} твърде силно и ги откъсва.`,
            `${author} удавя ${target} в бъчва с бира.`,
            `${author} удавя ${target} в вана с горещ шоколад. *Какво беше последното ти питие?*`,
            `${author} разкъсва ${target} с ръждив нож за масло. Ох!`,
            `${author} дава орео, пълно с паста за зъби, на ${target}, който се оказва алергичен към флуор. GGWP.`,
            `${author} се влюби в ${target}, след което буквално му разби сърцето.`,
            `${author} изстрелва свръхзвукова замразена пуйка по ${target}, убивайки го мигновено.`,
            `${author} забрави да остави прозореца на колата отворен, и ${target} умира от прегряване.`,
            `${author} забрави да направи двора на ${target} устойчив на зомбита... Изглежда, че зомбитата са се пирували снощи.`,
            `${author} кара ${target} да гледа аниме с него. ${target} не издържа.`,
            `${author} хваща ${target} и го пъхва в автоматична замразяваща машина със сок, настройвайки температурата на 100 Келвина, създавайки човешки ледени близалки.`,
            `${author} ме нае да убия ${target}, но не искам! ${target}`,
            `${author} прегръща ${target} твърде силно...`,
            `${author} хълк смашва ${target} в каша.`,
            `${author} убива ${target}, като му откъсва кожата от лицето и прави маска от нея.`,
            `${author} убива ${target} след часове мъчения.`,
            `${author} убива ${target} със свещник в библиотеката.`,
            `${author} убива ${target} с доброта.`,
            `${author} убива ${target} със собствения си крак.`,
            `${author} убива ${target} с брадва.`,
            `${author} натиска Delete. Това изтри ${target}.`,
            `${author} бута ${target} в студения вакуум на космоса.`,
            `${author} прегазва ${target} с PT Cruiser.`,
            `${author} стреля ${target} в главата.`,
            `${author} стреля в устата на ${target} с дъгов лазер, което кара главата на ${target} да експлодира с дъги, а ${target} се преражда като еднорог. :unicorn:`,
            `${author} застреля ${target}, използвайки Starkiller Base!`,
            `${author} сипва белина в лимонадата на ${target}.`,
            `${author} удушава ${target}.`,
            `${author} връзва ${target} за ICBM и го изпраща в Северна Корея.`,
            `${author} удря ${target} с убиващото проклятие... *Avada Kedavra!*`,
            `${author} откъсва устните на ${target} след целувка.`,
            `${author} е толкова "дебел", че срива гръдния кош на ${target}.`,
            `${author} се опитва да стреля в широката страна на хамбар, но пропуска и уцелва ${target} вместо това.`,
            `${author} пуска Goosebumps (2015 филм) на телевизора. ${target}, който е страхливец, умира от инфаркт.`,
            `${author} беше толкова swag, че ${target} умря заради това. #Swag`,
            `${author}, сигурен ли си, че искаш да убиеш ${target}? Те изглеждат приятни за мен.`,
            `${target} случайно кликна на popup реклама, която казва: \`Лекарите ни мразят, вижте най-добрия трик за умиране днес!\``,
            `${target} случайно се спъна и умря, докато ставаше, за да напише своето писмо за самоубийство.`,
            `${target} изяде парче екзотично масло. То беше толкова невероятно, че го уби.`,
            `${target} изяде ябълка и се оказа, че е направена от восък. Някой умря от отравяне с восък по-късно този ден.`,
            `${target} изяде твърде много лаксативи и се удави в собственото си лайно. Уф.`,
            `${target} изтече кръв, след като се опита да се качи на \`Най-глупавите моменти на хълма\`.`,
            `${target} си купи фиджет спинер и се удави в женско внимание.`,
            `${target} не може да бъде убит, защото е призрак.`,
            `${target} се задушава в кошче за боклук.`,
            `${target} се задушава с кокал от пиле.`,
            `${target} се задушава с Cheerios и умира. Какъв идиот...`,
            `${target} усилва музикалната система, само за да осъзнае, че звукът е на максимум, а песента е Baby на Justin Beiber...`,
            `${target} си вкарва семенна течност в окото, ослепява, бяга за помощ, но се забива на релсите и го прегазва влак.`,
            `${target} решава, че е добра идея да се бори с тигър, докато мирише на месо. Това не завършва добре.`,
            `${target} не направи достатъчно яко меме и беше пребит с камъни.`,
            `${target} умира, след като мастурбира 50 пъти подред без почивка.`,
            `${target} умира, след като играе 90 часа без движение или ядене.`,
            `${target} умира, след като си играе с опасен фиджет спинер.`,
            `${target} умира, след като осъзнава колко лоша е тяхната граматика.`,
            `${target} умира, след като се опитва да направи по-добро меме от Dank Memer.`,
            `${target} умира почтено. Смърт чрез snoo snoo.`,
            `${target} умира, защото RemindMeBot забрави да им напомни да дишат.`,
            `${target} умира, защото започва да си играе с фиджет спинер, но осъзнава, че е 2016 и започва да мастурбира на старата вещица от "Снежанка", а Обама започва да коси лехата им и те изхвърчат през прозореца, където ги разкъсва косачката на Обама.`,
            `${target} умира поради ${author}, който е толкова глупав.`,
            `${target} умира, защото яде твърде много хотдогове в подготовка за срещата си.`,
            `${target} умира, ядейки изтекла и заразена сурова риба със най-мръсния ориз в света като суши, докато е пронизван от 9-инчов пирон. Соевият сос беше от котешка урина.`,
            `${target} умира от високо съдържание на сол.`,
            `${target} умира от бърз удар в мозъка.`,
            `${target} умира от трагично много лошо succ.`,
            `${target} умира, правейки Ice Bucket Challenge.`,
            `${target} умира от твърде много вода. Явно е възможно!`,
            `${target} умира, ядейки бодли от кактус.`,
            `${target} умира, ядейки твърде много задници.`,
            `${target} умира, ядейки твърде много хляб :/`,
            `${target} умира от ебола.`,
            `${target} умря от недостиг на мемета :/`,
            `${target} умря, защото не яде достатъчно задници.`,
            `${target} умря, защото не мастурбира достатъчно. (Трябва баланс, момчета)`,
            `${target} умря, защото репостна в грешния квартал.`,
            `${target} умря от шитене в продължение на 36 часа.`,
            `${target} умря, след като гълта камъни твърде бързо.`,
            `${target} умря от твърде много изгаряния от слънцето.`,
            `${target} умря, защото мастурбира твърде много. (Трябва баланс, момчета)`,
            `${target} умря от oversucc.`,
            `${target} умря, докато тества водородна бомба. Няма нищо за погребване.`,
            `${target} умря, докато слушаше 'It's every day bro'.`,
            `${target} умря, докато играеше хопскоч на *привидно* деактивирани земни мини.`,
            `${target} умря, докато се опитваше да намери града Англия.`,
            `${target} умря. ООФ.`,
            `${target} умря, след като погълна клечка за зъби.`,
            `${target} умря от ръцете на ${author}.`,
            `${target} умря, защото използваше боби пин, за да вдигне миглите си.`,
            `${target} умря, защото беше просто твърде ядосан.`,
            `${target} умря, като прокле християнски Minecraft сървър.`,
            `${target} умря поради липса на приятели.`,
            `${target} умря от лош succ.`,
            `${target} умря, защото прекали с dabbing.`,
            `${target} умря, защото прекали с dabbing.`,
            `${target} умря, защото прояви неуважение към жените.`,
            `${target} умря, защото беше просто лош, неприятен човек.`,
            `${target} умря, защото публикува нормални мемета.`,
            `${target} умря от тежка неприязън към пясък. Той е груб, дразнещ и влиза навсякъде.`,
            `${target} умря, защото гледаше Emoji Movie и му хареса.`,
            `${target} умря в ужасен инцидент, организиран от ${author}.`,
            `${target} умря на север от стената и се превърна в бял уокър.`,
            `${target} умря от СПИН.`,
            `${target} умря от дизентерия.`,
            `${target} умря от естествени причини.`,
            `${target} умря от глад.`,
            `${target} умря чрез смъртоносна инжекция, след като уби ${author} и семейството му.`,
            `${target} умря, но не позволявайте това да ви разсее от факта, че през 1998 г. The Undertaker хвърли Mankind от Hell In A Cell и той се разби на 16 фута през масата за коментатори.`,
            `${target} умря.`,
            `След борба, ${target} уби ${author}.`,
            `${target} изчезна от вселената.`,
            `${target} изпи токсична сода, преди да бъде изтеглена от пазара.`,
            `${target} изпусна телефон Nokia върху лицето си и си разцепи черепа.`,
            `${target} се удави в собствените си сълзи.`,
            `${target} изяде твърде много copypasta и експлодира.`,
            `${target} падна от скала, докато играеше Pokemon Go. Добра работа, че държа носа си в този мъничък телефон. :iphone:`,
            `${target} падна в яма с ядосани феминистки.`,
            `${target} беше блъснат от кола.`,
            `${target} беше намушкан от ${author}.`,
            `${target} беше ударен от мълния.`,
            `${target} отиде на геноцид, а Sans напълно разби ${target}!`,
            `${target} влезе в ножова битка с папата. Един от тях сега е в ада.`,
            `${target} беше настъпан от слон.`,
            `${target} умря от ядене на твърде много задници.`,
            `${target} получи инсулт след тъжен и мизерен живот. След това беше изяден от многото си котки.`,
            `${target} беше признат за виновен. Време е за екзекуция!`,
            `${target} изяде лоша китайска храна и плати най-високата цена.`,
            `${target} беше отвлечен от извънземни, а правителството го уби, за да прикрие случая.`,
            `${target} умря от ръцете на ${author}.`,
            `${target} беше инжектиран с шоколадов сироп, който го мутира в човек, направен от шоколад. Докато работи в детска градина, бебетата го изядоха. :chocolate_bar:`,
            `${target} беше убит от заек с жестока жилка.`,
            `${target} беше убит от собствената си глупост.`,
            `${target} беше убит по време на обир, който се обърка.`,
            `${target} не може да бъде убит. О, чакайте, ${author} все пак го убива.`,
            `${target} беше толкова тъп, че се задуши от кислород.`,
            `${target} беше натъпкан в костюм от Фреди на нощната охрана. О, не отново тези аниматроници!`,
            `${target} беше засмукан в Minecraft. ${target}, като новак в така наречения реален Minecraft, вижда екрана Game Over.`,
            `${target} се самоубива, след като видя нормалните мемета, публикувани от ${author}.`,
            `${target} се самоубива, след като осъзнава колко тъп е ${author}.`,
            `${target} оцелява, въпреки опита за убийство на ${author}.`,
            `${target} губи волята за живот.`,
            `${target} натиска произволен бутон и се телепортира на височина от 100 метра, където пада към неизбежната си смърт. Урокът: Не натискайте произволни бутони.`,
            `${target} чете мемета, докато не умре.`,
            `${target} си изтръгва сърцето...`,
            `${target} си изтръгва сърцето, за да покаже любовта си към ${author}.`,
            `${target} крещи от ужас, докато случайно призовава Ктулху, изговаряйки случайни латински думи. Ктулху хваща ${target} за десния крак и го отвежда в измерението си, казвайки: \`Скъпа, вечерята е готова!\``,
            `${target} се подхлъзва в банята и се задушава с пердето на душа.`,
            `${target} се подхлъзва на бананова кора и пада по стълбите.`,
            `${target} върти фиджет спинер, а когато спира, умира...`,
            `${target} настъпва George Foreman и умира от синдрома на вафлен крак.`,
            `${target} получава стрела в коляното. И навсякъде другаде.`,
            `${target} говори грубо с модераторите и бива унищожен от чука за бан.`,
            `${target} накланя шапката си твърде много и пада върху релсите на идващо метро.`,
            `${target} се опитва да бъде сръчен, но случайно се порязва с ножица. :scissors:`,
            `${target} се опитва да стане известен в YouTube, като стриймва глупости. Скачане с парашут, докато е вързан за хладилник.`,
            `${target} се опитва да надбяга влак, но влакът печели.`,
            `${target} се опитва да избере свещения граал. Той избра... погрешно.`,
            `${target} се опитва да играе на улицата...`,
            `${target} се спъва в собствените си връзки на обувките и умира.`,
            `${target} се противопостави на Клинтънови и внезапно изчезна.`,
            `${target} беше жител на Алдераан, преди Дарт Вейдър да унищожи планетата...`,
            `${target} беше обвинен в кражба на короната на Нептун...`,
            `${target} зареждаше своя Samsung Galaxy Note 7...`,
            `${target} беше изяден жив от мравки.`,
            `${target} получи шанс да синтезира елемент 119 (Ununennium) и да го кръсти на свое име, но се провали. Почивай в мир.`,
            `${target} беше убит от ${author} с бебешки кърпички.`,
            `${target} беше убит от ${author} и всички го знаят, но няма доказателства.`,
            `${target} беше разчленен от ${author}, а вътрешностите им вече са Ennard.`,
            `${target} беше телепортиран в времевата линия, където Jurassic World е реален, и беше изяден жив от Indominus Rex.`,
            `${target} беше хвърлен в трошачката на боклукчийски камион от ${author}.`,
            `${target} си вървеше нормално, когато с ъгълчето на окото си видя как някой направи bottle flip и dab, което доведе до инсулт.`,
            `${target} гледаше Emoji Movie и умря от чисто неудобство.`,
            `${target} отиде на разходка с балон, пълен с олово.`,
            `След като ${author} го бутна в океана, ${target} беше изяден от акула.`,
            `След като роблокс деца нахлуха в сървъра, ${target} умря от рак.`,
            `СПИН, ${target} умря от СПИН.`,
            `Призовавайки божествени сили, ${author} поразява ${target} и техните езически начини.`,
            `В изненадващ обрат на събитията, аз **не** убивам ${target}.`,
            `не ти`,
            `Нашият господ и спасител Гейбън удря ${target} с мълния.`,
            `Съжалявам, ${author}, не обичам да убивам хора.`,
            `Куршумът пропусна Харамбе и уцели ${target}. Да живее Харамбе!`,
            `Докато прави колоноскопия на слон, ${target} си заклещва главата в ректума на слона и се задушава.`,

            // ==== [[Original Start]] ====
            // ` after a long day, plops down on the couch with ${target} and turns on The Big Bang Theory. After a Sheldon Cooper joke, ${target} laughs uncontrollably as they die.`,
            // `${author} Alt+F4'd ${target}.exe!`,
            // `${author} attempted to play a flute, exploding the head of ${target}.`,
            // `${author} blew his ear drums out listening to music too hard.`,
            // `${author} challenges ${target} to a fist fight to the death. ${target} wins.`,
            // `${author} cleaves the head of ${target} with a keyboard.`,
            // `${author} crushes ${target} with a fridge.`,
            // `${author} decapitates ${target} with a sword.`,
            // `${author} drags ${target}s ears too hard and rips them off.`,
            // `${author} drowns ${target} in a beer barrel.`,
            // `${author} drowns ${target} in a tub of hot chocolate. *How was your last drink?*`,
            // `${author} eviscerates ${target} with a rusty butter knife. Ouch!`,
            // `${author} feeds toothpaste-filled oreos to ${target}, who were apparently allergic to fluorine. GGWP.`,
            // `${author} fell in love with ${target} then broke his heart literally.`,
            // `${author} fires a supersonic frozen turkey at ${target}, killing them instantly.`,
            // `${author} forgot to leave the car door window open and ${target} dies from overheating`,
            // `${author} forgot to zombie-proof ${target} lawn... Looks like zombies had a feast last night.`,
            // `${author} gets ${target} to watch anime with them. ${target} couldn't handle it.`,
            // `${author} grabs ${target} and shoves them into an auto-freeze machine with some juice and sets the temperature to 100 Kelvin, creating human ice pops.`,
            // `${author} hired me to kill you, but I don't want to! ${target}`,
            // `${author} hugs ${target} too hard..`,
            // `${author} hulk smashes ${target} into a pulp.`,
            // `${author} killed ${target} by ripping the skin off of their face and making a mask out of it.`,
            // `${author} kills ${target} after hours of torture.`,
            // `${author} kills ${target} with a candlestick in the study`,
            // `${author} kills ${target} with kindness`,
            // `${author} kills ${target} with their own foot.`,
            // `${author} murders ${target} with an axe.`,
            // `${author} pressed delete. It deleted ${target}`,
            // `${author} pushes ${target} into the cold vacuum of space.`,
            // `${author} runs ${target} over with a PT Cruiser.`,
            // `${author} shoots ${target} in the head.`,
            // `${author} shoots in ${target} mouth with rainbow laser, causing ${target} head to explode with rainbows and ${target} is reborn as unicorn. :unicorn:`,
            // `${author} shot ${target} using the Starkiller Base!`,
            // `${author} slips bleach into ${target}'s lemonade.`,
            // `${author} strangles ${target}.`,
            // `${author} straps ${target} to an ICBM and sends them to North Korea along with it.`,
            // `${author} strikes ${target} with the killing curse... *Avada Kedavra!*`,
            // `${author} tears off ${target}s lips after a kiss.`,
            // `${author} thicc and collapses ${target}'s rib cage`,                
            // `${author} tries to shoot the broad side of a barn, misses and hits ${target} instead.`,
            // `${author} turns on Goosebumps(2015 film) on the TV. ${target} being a scaredy-cat, dies of an heart attack.`,
            // `${author} was so swag that ${target} died due to it. #Swag`,
            // `${author}, are you sure you want to kill ${target}? They seem nice to me.`,
            // `${target} accidentally clicked on a popup ad that reads \`Doctors hate us, see the one best trick for dying today!\``,
            // `${target} accidentally tripped and died while getting up to write their suicide note.`,
            // `${target} ate a piece of exotic butter. It was so amazing that it killed them.`,
            // `${target} ate an apple and turned out it was made out of wax. Someone died from wax poisoning later that day.`,
            // `${target} ate too many laxatives and drowned in their own shit. Ew.`,
            // `${target} bleeds out after trying to get on \`Dumbest hillbilly moments\`.`,
            // `${target} bought a fidget spinner and drowned in pussy.`,
            // `${target} can't be killed, as they are a ghost.`,
            // `${target} chokes in a trash can.`,
            // `${target} chokes on a chicken bone.`,
            // `${target} chokes on cheerios and dies. What an idiot...`,
            // `${target} cranks up the music system only to realize the volume was at max and the song playing was Baby by Justin Beiber...`,
            // `${target} cums in eye, goes blind, runs for help but ran straight onto train tracks and gets plowed by a train.`,
            // `${target} decided it was a good idea to fight a tiger while smelling like meat. It did not end well.`,
            // `${target} did not make a meme dank enough and was stoned.`,
            // `${target} died after fapping 50 times in a row with no break.`,
            // `${target} died after gaming for 90 hours straight without moving or eating.`,
            // `${target} died after playing with an edgy razor blade fidget spinner.`,
            // `${target} died after realizing how shitty their grammar was`,
            // `${target} died after trying to out-meme Dank Memer.`,
            // `${target} died an honorable death. Death by snoo snoo.`,
            // `${target} died because RemindMeBot forgot to remind them to breathe`,
            // `${target} died because they started playing with a fidget spinner but they realise its 2016 so you start fapping to the old witch in snow white and obama starts mowing their lawn and they jump out of the window and get ripped to pieces by Obama's lawn mower`,
            // `${target} died due to ${author} being so stupid`,
            // `${target} died due to eating WAY too many hotdogs in preparation for their date Friday night.`,
            // `${target} died eating expired and infected raw fish with the filthiest rice in the world as sushi while being constantly stabbed in the scrotum with a 9inch nail sharp enough to stab through kevlar. The soy sauce was cat piss.`,
            // `${target} died from a high salt intake`,
            // `${target} died from a swift kick to the brain.`,
            // `${target} died from a tragic amount of bad succ`,
            // `${target} died from doing the ice bucket challenge.`,
            // `${target} died from drinking too much water Huh, I guess it IS possible!.`,
            // `${target} died from eating cactus needles.`,
            // `${target} died from eating too much ass.`,
            // `${target} died from eating too much bread :/`,
            // `${target} died from ebola.`,
            // `${target} died from meme underdose :/`,
            // `${target} died from not eating enough ass.`,
            // `${target} died from not whacking it enough. (There's a healthy balance, boys)`,
            // `${target} died from reposting in the wrong neighborhood`,
            // `${target} died from shitting for 36 hours straight.`,
            // `${target} died from swallowing rocks too fast`,
            // `${target} died from too many sunburns.`,
            // `${target} died from whacking it too much. (There's a healthy balance, boys)`,
            // `${target} died of oversucc`,
            // `${target} died when testing a hydrogen bomb. There is nothing left to bury.`,
            // `${target} died while listening to 'It's every day bro'`,
            // `${target} died while playing hopscotch on *seemingly* deactivated land mines.`,
            // `${target} died while trying to find the city of England`,
            // `${target} died. OOF`,
            // `${target} dies after swallowing a toothpick.`,
            // `${target} dies at the hands of ${author}.`,
            // `${target} dies because they used a bobby pin to lift their eyelashes`,
            // `${target} dies because they were just too angry.`,
            // `${target} dies by swearing on a Christian Minecraft server`,
            // `${target} dies due to lack of friends.`,
            // `${target} dies from bad succ.`,
            // `${target} dies from dabbing too hard.`,
            // `${target} dies from dabbing too hard`,
            // `${target} dies from disrespecting wahmen.`,
            // `${target} dies from just being a bad, un-likeable dude.`,
            // `${target} dies from posting normie memes.`,
            // `${target} dies from severe dislike of sand. It's coarse and rough and irritating it gets everywhere`,
            // `${target} dies from watching the emoji movie and enjoying it.`,
            // `${target} dies in a horrible accident, and it was engineered by ${author}.`,
            // `${target} dies north of the wall and transforms into a white walker`,
            // `${target} dies of AIDS.`,
            // `${target} dies of dysentery.`,
            // `${target} dies of natural causes.`,
            // `${target} dies of starvation.`,
            // `${target} dies on death row via lethal injection after murdering ${author} and their family.`,
            // `${target} dies, but don't let this distract you from the fact that in 1998, The Undertaker threw Mankind off Hell In A Cell, and plummeted 16 ft through an announcer’s table`,
            // `${target} dies.`,
            // `After a struggle, ${target} kills ${author}`,
            // `${target} disappeared from the universe.`,
            // `${target} drank some toxic soda before it was recalled.`,
            // `${target} dropped a Nokia phone on their face and split their skull.`,
            // `${target} drowned in their own tears.`,
            // `${target} eats too much copypasta and explodes`,
            // `${target} fell down a cliff while playing Pokemon Go. Good job on keeping your nose in that puny phone. :iphone:`,
            // `${target} fell into a pit of angry feminists.`,
            // `${target} gets hit by a car.`,
            // `${target} gets stabbed by ${author}`,
            // `${target} gets struck by lightning.`,
            // `${target} goes genocide and Sans totally dunks ${target}!`,
            // `${target} got into a knife fight with the pope. One of them is in hell now.`,
            // `${target} got stepped on by an elephant.`,
            // `${target} died from eating too much ass.`,
            // `${target} has a stroke after a sad miserable existence. They are then devoured by their ample cats.`,
            // `${target} has been found guilty, time for their execution!`,
            // `${target} has some bad chinese food, and pays the ultimate price.`,
            // `${target} is abducted by aliens, and the government kills them to cover it up.`,
            // `${target} is dead at the hands of ${author}.`,
            // `${target} is injected with chocolate syrup, which mutates them into a person made out of chocolate. While doing a part-time job at the Daycare, they are devoured by the hungry babies. :chocolate_bar:`,
            // `${target} is killed by a rabbit with a vicious streak a mile wide`,
            // `${target} is killed by their own stupidity.`,
            // `${target} is killed in a robbery gone wrong.`,
            // `${target} is not able to be killed. Oh, wait, no, ${author} kills them anyway.`,
            // `${target} is so dumb that they choked on oxygen.`,
            // `${target} is stuffed into a suit by Freddy on their night guard duty. Oh, not those animatronics again!`,
            // `${target} is sucked into Minecraft. ${target}, being a noob at the so called Real-Life Minecraft faces the Game Over screen.`,
            // `${target} killed themselves after seeing the normie memes that ${author} posts.`,
            // `${target} kills themselves after realizing how dumb ${author} is.`,
            // `${target} lives, despite ${author}'s murder attempt.`,
            // `${target} loses the will to live`,
            // `${target} presses a random button and is teleported to the height of 100m, allowing them to fall to their inevitable death. Moral of the story: Don't go around pressing random buttons.`,
            // `${target} reads memes till they die.`,
            // `${target} ripped his heart out..`,
            // `${target} ripped their own heart out to show their love for ${author}.`,
            // `${target} screams in terror as they accidentally spawn in the cthulhu while uttering random latin words. Cthulhu grabs ${target} by the right leg and takes them to his dimension yelling, \`Honey, Dinner's ready!\``,
            // `${target} slipped in the bathroom and choked on the shower curtain.`,
            // `${target} slips on a banana peel and falls down the stairs.`,
            // `${target} spins a fidget spinner and when it stops he dies...`,
            // `${target} steps on a george foreman and dies of waffle foot.`,
            // `${target} takes an arrow to the knee. And everywhere else.`,
            // `${target} talked back to mods and got destroyed by the ban hammer.`,
            // `${target} tips his fedora too far and falls onto the tracks of an oncoming subway.`,
            // `${target} tried to get crafty, but they accidentally cut themselves with the scissors.:scissors:`,
            // `${target} tried to get famous on YouTube by live-streaming something dumb. Skydiving while chained to a fridge.`,
            // `${target} tried to outrun a train, the train won.`,
            // `${target} tried to pick out the holy grail. He chose... poorly.`,
            // `${target} tried to play in the street...`,
            // `${target} trips over his own shoe laces and dies.`,
            // `${target} vocally opposed the Clintons and then suddenly disappeared.`,
            // `${target} was a resident of Alderaan before Darth Vader destroyed the planet...`,
            // `${target} was accused of stealing Neptune's crown...`,
            // `${target} was charging their Samsung Galaxy Note 7...`,
            // `${target} was eaten alive by ants`,
            // `${target} was given a chance to synthesize element 119 (Ununennium) and have it named after them, but they messed up. R.I.P.`,
            // `${target} was killed by ${author} with baby wipes.`,
            // `${target} was murdered by ${author} and everyone knows it, but there is no proof.`,
            // `${target} was scooped by ${author} and their innards are now Ennard.`,
            // `${target} was teleported to the timeline where Jurassic World was real and they were eaten alive by the Indominus Rex.`,
            // `${target} was thrown in the crusher of a trash truck by ${author}.`,
            // `${target} was walking normally when out of the corner of their eye they saw someone do a bottle flip and dab causing ${target} to have a stroke.`,
            // `${target} watched the Emoji Movie and died of sheer cringe.`,
            // `${target} went on a ride with a lead balloon.`,
            // `After getting pushed into the ocean by ${author}, ${target} is eaten by a shark.`,
            // `After raid of roblox kids entered the server, ${target} died of cancer.`,
            // `Aids, ${target} died from aids.`,
            // `Calling upon the divine powers, ${author} smites ${target} and their heathen ways`,
            // `In a sudden turn of events, I **don't** kill ${target}.`,
            // `no u`,
            // `Our lord and savior Gaben strikes ${target} with a lighting bolt.`,
            // `Sorry, ${author}, I don't like killing people.`,
            // `The bullet missed Harambe and hit ${target} instead. Yay for Harambe!`,
            // `While performing colonoscopy on an elephant, ${target} gets their head stuck in the elephants rectum and chokes.`,
            // ==== [[Original END]] ====
          ];

        const death = kills[Math.floor(Math.random() * kills.length)];

        // Create an embed
        const embed = new EmbedBuilder()
            .setTitle('☠️︱Смъртта на един герой...')
            .setDescription(`${author} убива ${target}!\n\n${death}`)
            .setColor('#ff0000') // Red color for the death theme
            .setTimestamp();

        // Send the embed
        interaction.reply({ embeds: [embed] });
    }
}